# Generated by Django 5.0.1 on 2024-01-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=18, verbose_name='enter your name : ')),
                ('last_name', models.CharField(max_length=18)),
                ('phone', models.BigIntegerField()),
            ],
        ),
    ]
